# Generated by Django 3.1.6 on 2021-04-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210403_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='msg_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
