# Generated by Django 3.1.6 on 2021-04-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210403_2043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
