# Generated by Django 3.1.6 on 2021-04-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210403_2057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
