# Generated by Django 3.1.6 on 2021-04-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Touch',
        ),
    ]
