# Generated by Django 3.1.6 on 2021-04-04 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210404_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
