# Generated by Django 3.1.6 on 2021-04-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='product_id',
        ),
    ]
