# Generated by Django 3.1.6 on 2021-04-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20210404_1301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact2',
        ),
    ]
